language: java

# Use container-based infrastructure:
sudo: false

# Keep Maven local repository between builds:
cache:
  directories:
    - $HOME/.m2

jdk:
  - openjdk8
  - openjdk10
  - openjdk11

script:
  - mvn clean package
